### ISSUE TITLE
Material Design Theme Not Followed!

### ISSUE THREAD

**Issue by G0ldenSp00n** [G0ldenSp00n/Group-Developing-Project#6]
We aren't following the Material design theme right on the developers page!  We need to change them from cards to grid tiles.
![error](https://cloud.githubusercontent.com/assets/6732797/9043286/3d74d9a8-39c9-11e5-9ab2-112ecace15a6.PNG)
As you can see by the photo above, we should be using grid tiles, which are the tiles with the tinted base!  Please fix this so that it just says the persons name, but clicking on a tile will link to the persons profile!
![developers](https://cloud.githubusercontent.com/assets/6732797/9043323/7d8494f2-39c9-11e5-9175-34b7ca18aca4.PNG)
Those should all be grid tiles, thanks for fixing it Sean.  And once you do close this issue. Thanks!

**Comment by seandoesftw** [comment]
cant fix currently will late tonight maybe.
